### ISSUE TITLE
Thank you for improving vscode script

### ISSUE THREAD

**Issue by samfux84** [jkwmoore/vscoderemote_sharc#1]
This is not really an issue, just a message to @jkwmoore 

@jkwmoore Thank you for adapting/improving the script from https://gitlab.ethz.ch/sfux/VSCode_remote_HPC.

I like your changes to the clean up part (terminating the batch job and the SSH tunnel) a lot. I thought about using an SSH control socket but I did not find the time to further work on this. Your idea to store the pid of the SSH tunnel and to keep the script running until the user terminates it is clean and beautiful (requires only very little additional bash code). We will definitely add your changes to the original script.

Just for your information, Microsoft is soon releasing a vscode-server, which can be used instead of the code-server fork. Currently, it is in some closed beta testing phase, but another user (Florian Pfaff,  from the KIT in Karlsruhe, Germany) joined the beta testing phase and tried the setup with the vscode-server and reports that it is working fine.

This way, users can use the Microsoft version and not the fork (code-server), which would also allow them to use the Microsoft market place for the VSCode extensions instead of the one from code-server that only has the open-source extensions.

Not sure if this might be interesting for you too, but we use a very similar setup for running jupyter notebooks through the batch system of our cluster:

https://gitlab.ethz.ch/sfux/Jupyter-on-Euler-or-Leonhard-Open

It basically uses the same logic as the VSCode script (start a batch job, setup an SSH tunnel and connect the local browser to the server running on the cluster). We are also planning to do a similar setup for the RStudio server, such that users can run RStudio sessions in their browser that connect to an RStudio server running as a batch job.

Thank you and best regards,

Samuel Fux

**Comment by jkwmoore** [comment]
Many thanks for the heads up! At some stage I am likely to convert this to the SLURM scheduler and will probably fold in the change to `vscode-server` at that time.

For now at least, we approach our Jupyter notebook jobs with Jupyterhub: https://docs.hpc.shef.ac.uk/en/latest/hpc/jupyterhub.html

This said, we will likely be moving to providing for most GUI or WebUI apps in the future with Open OnDemand: https://openondemand.org/run-open-ondemand

Open OnDemand looks very promising so I'd recommend having a look!

**Comment by samfux84** [comment]
> At some stage I am likely to convert this to the SLURM scheduler and will probably fold in the change to vscode-server at that time.

We are already working on this, as we just switched from LSF to SLURM on our cluster (I will wait with the change from code-server to vscode-server until there is a public release by Microsoft). We are still facing a few small issues with the change to SLURM, but they should soon be resolved. I will let you know as soon as we have a working version.

Thank you for the hint with OnDemand, I will definitely check this as well.
