### ISSUE TITLE
VS Code Debugging script

### ISSUE THREAD

**Issue by nikishe** [jkwmoore/vscoderemote_sharc#2]
https://github.com/jkwmoore/vscoderemote_sharc/blob/ad5203290d8d8f7419f4508f94ddecb844868261/start_vscode.sh#L338

Swap this with:

/home/$VSC_USERNAME

To avoid issues caused by different local usernames.

**Comment by jkwmoore** [comment]
Ty! Resolved in df87dcd1f7adcea6111d549dcc0cb0c869456c27.
